export const testersArry  = [
    {
      name: "Mei Lai",
      role: "QA Automation Specialist",
      verified: "Verified Expert in Selenium and Automated Testing Frameworks",
      style: "text-[5px]  ",
      company: "ZenWave Systems",
      image: "Images/g1.svg",
      size: " w-[75%]    text-[5px]   ",
      move: " mx-5",
    },
    {
      name: "Nguyen Tran",
      role: "QA Automation Engineer",
      company: "BrightCode Systems",
      verified: "Verified Expert in End-to-End Testing and Automated Frameworks",
      style: "text-[5px] ",
      image: "Images/g2.svg",
      size: "w-[80%] text-[5px]  ",
      move: " mt-32 ",
    },
    {
      name: "Emma Johnson",
      role: "Senior QA Engineer",
      company: "ApexSoft Solutions",
      verified: "Verified Expert in Functional Testing and Regression Suites",
      style: "text-[5px]",
      image: "Images/g3.svg",
      size: "w-[100%] text-[5px]  ",
      move: "mt-24 ",
    },
    {
      name: "Ahmad Faizal",
      role: "QA Analyst",
      company: "FlowBridge Labs",
      verified: "Verified Expert in Manual Testing and API Validation",
      style: "text-[5px]",
      image: "Images/g4.svg",
      size: "w-[80%]    text-[5px] ",
      move: " mx-[-8px] relative bottom-24  ",
    },
    {
      name: "Daniel White",
      role: "QA Team Lead",
      company: "ZenWave Systems",
      verified:
        "Verified Expert in and Requirements Validation",
      style: " text-[5px]",
      image: "Images/g5.svg",
      size: "w-[70%] text-[5px]  ",
      move: " mt-10  ",
    },
    {
      name: "Rohit Sharma",
      role: "Principal QA Engineer",
      verified:
        "Verified Expert in Performance Testing and Requirements Validation",
      style: "  text-[10px]",
      company: "CodeClimb Innovations",
      image: "Images/g6.svg",
      size: "w-[110%]  ",
    },
    {
      name: "Emma Johnson",
      role: "Senior QA Engineer ",
      company: "ApexQA Solutions",
      verified: "Verified Expert in API Testing and Test Case Writing",
      style: "text-[4px]",
      image: "Images/g7.svg",
      size: "w-[60%] text-[4px]",
      move: " relative bottom-24  ",
    },
  ];