import type { Metadata } from "next";

import "./globals.css";
import Footer from "./Components/footer";



export const metadata: Metadata = {
  title: "Reqops",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#EDF0F5]">
        {children}
        <Footer />
      </body>
    </html>
  );
}
